#!/usr/bin/env python3
"""Recompute the letter's tables, scalar claims, and figures from archived runs."""

import argparse
import csv
import json
import math
import statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SCENARIOS = ["unseen_sparse", "unseen_normal", "unseen_saturated", "unseen_low_mcs",
             "unseen_active_4", "unseen_active_7"]
NAMES = ["Sparse", "Normal", "Saturated", "Low MCS", "4 STAs", "7 STAs"]
POLICIES = ["rr_default", "max_backlog", "oracle_throughput", "ml_throughput",
            "oracle_delay", "ml_delay"]


def mean_ci(values):
    values = list(values)
    if len(values) != 10:
        raise ValueError("The archived letter campaign requires ten paired runs per cell")
    return statistics.fmean(values), 2.262 * statistics.stdev(values) / math.sqrt(10)


def load_results(directory):
    with (directory / "runs.csv").open(newline="") as stream:
        rows = list(csv.DictReader(stream))
    indexed = {(r["scenario"], r["policy"], int(r["seed_index"])): r for r in rows}
    expected = {(s, p, k) for s in SCENARIOS for p in POLICIES for k in range(10)}
    if len(rows) != 360 or set(indexed) != expected:
        raise ValueError("Missing, duplicate, or unexpected campaign rows")
    for (s, p, k), row in indexed.items():
        if int(row["seed"]) != 920000 + k:
            raise ValueError(f"Unpaired RNG run in {s}/{p}/{k}")
    metrics = ["throughput_mbps", "delay_mean_ms", "delay_p99_ms", "fairness"]
    cells = {}
    effects = {}
    for s in SCENARIOS:
        for p in POLICIES:
            cells[s, p] = {m: mean_ci(float(indexed[s, p, k][m]) for k in range(10))
                           for m in metrics}
        for baseline in ["rr_default", "max_backlog", "oracle_throughput"]:
            effects[s, baseline] = {
                m: mean_ci(float(indexed[s, "ml_throughput", k][m]) -
                           float(indexed[s, baseline, k][m]) for k in range(10))
                for m in metrics
            }
    archived = json.loads((directory / "summary.json").read_text())
    for record in archived:
        for metric in metrics:
            actual = cells[record["scenario"], record["policy"]][metric][0]
            if not math.isclose(actual, record[metric + "_mean"], abs_tol=1e-9):
                raise ValueError("CSV and archived summary disagree")
    return indexed, cells, effects


def table(path, caption, label, header, rows, columns):
    content = ["% Generated by source/analyze.py.", r"\begin{table}[t]",
               r"\caption{" + caption + "}", r"\label{" + label + "}",
               r"\centering\footnotesize", r"\setlength{\tabcolsep}{3pt}",
               r"\begin{tabular}{" + columns + "}", r"\toprule",
               " & ".join(header) + r" \\", r"\midrule"]
    content.extend(" & ".join(row) + r" \\" for row in rows)
    content.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    path.write_text("\n".join(content))


def generate(directory, output, plots=True):
    output.mkdir(parents=True, exist_ok=True)
    indexed, cells, effects = load_results(directory)
    latency = json.loads((directory / "serial_latency.json").read_text())
    if len(latency["rows"]) != 18:
        raise ValueError("Expected eighteen serial timing runs")
    for metric, value in latency["summary"].items():
        if metric == "decision_global_max_us":
            actual = max(row["decision_max_us"] for row in latency["rows"])
        else:
            actual = statistics.fmean(row[metric] for row in latency["rows"])
        if not math.isclose(actual, value, abs_tol=1e-9):
            raise ValueError(f"Serial summary mismatch: {metric}")

    table(output / "throughput.tex", "Received UDP throughput (Mbps), ten paired runs",
          "tab:throughput", ["Scenario", "RR4", "Max-Q", "O-T", "L-T", "O-A", "L-A"],
          [[name] + [f"{cells[s,p]['throughput_mbps'][0]:.2f}" for p in POLICIES]
           for s, name in zip(SCENARIOS, NAMES)], "lrrrrrr")
    table(output / "delay.tex", "Delay of packets received in the measurement window (ms)",
          "tab:delay", ["Scenario", "RR4 mean", "L-T mean", "RR4 p99", "L-T p99"],
          [[name] + [f"{cells[s,p][metric][0]:.2f}"
                     for metric in ["delay_mean_ms", "delay_p99_ms"]
                     for p in ["rr_default", "ml_throughput"]]
           for s, name in zip(SCENARIOS, NAMES)], "lrrrr")
    table(output / "scenarios.tex", "Native evaluation scenarios; all datagrams are 1,000 bytes",
          "tab:scenarios", ["Scenario", "$N$", "MCS", "$b$", r"$\eta$", "Total Mbps"],
          [[name, indexed[s,"rr_default",0]["stations"], indexed[s,"rr_default",0]["mcs"],
            b, indexed[s,"rr_default",0]["load_skew"],
            f"{float(indexed[s,'rr_default',0]['offered_mbps']):.1f}"]
           for s, name, b in zip(SCENARIOS, NAMES, ["0.7", "5.5", "16", "5", "24", "12"])],
          "lrrrrr")
    components = [("State/features", "state"), ("Inference", "inference"),
                  ("Projection", "projection"), ("Decision hook", "decision")]
    table(output / "timing.tex", r"Serial host timing: means across 18 runs ($\mu$s)",
          "tab:timing", ["Component", "Mean", "Mean of run p99s"],
          [[name, f"{latency['summary'][key + '_mean_us']:.1f}",
            f"{latency['summary'][key + '_p99_us']:.1f}"] for name, key in components], "lrr")
    macros = {}
    for objective, prefix in [("throughput", "T"), ("delay", "A")]:
        model = json.loads((ROOT / "models" / objective / "training_metrics.json").read_text())
        for field, suffix in [("rows", "Rows"), ("training_rows", "TrainRows"),
                              ("validation_rows", "ValidationRows")]:
            macros[prefix + suffix] = f"{model[field]:,}"
        macros[prefix + "Exact"] = f"{100 * model['metrics']['raw_exact_action_accuracy']:.2f}"
        macros[prefix + "ActiveAccuracy"] = f"{100 * model['metrics']['active_sta_accuracy']:.2f}"
    macros["ModelBytes"] = f"{(ROOT / 'models/throughput/scheduler_weights.bin').stat().st_size:,}"
    macros["OracleGap"] = f"{max(abs(effects[s, 'oracle_throughput']['throughput_mbps'][0]) for s in SCENARIOS):.4f}"
    for metric, macro in [("inference_mean_us", "InferenceMean"),
                          ("decision_mean_us", "DecisionMean"),
                          ("decision_p99_us", "DecisionPninetyNine"),
                          ("decision_global_max_us", "DecisionMaximum")]:
        macros[macro] = f"{latency['summary'][metric]:.1f}"
    macros["MissPercent"] = f"{100*latency['summary']['decision_deadline_miss_rate']:.2f}"
    macros["FallbackMean"] = f"{latency['summary']['learned_fallbacks']:.2f}"
    (output / "numbers.tex").write_text("% Generated by source/analyze.py.\n" + "".join(
        "\\newcommand{\\" + key + "}{" + value + "}\n" for key, value in macros.items()))
    audit = {
        "network_runs": len(indexed), "serial_runs": len(latency["rows"]),
        "confidence_intervals": "paired Student-t, n=10, critical value 2.262",
        "effects": [{"scenario": s, "baseline": b,
                     **{m: {"mean": v[0], "ci95_half_width": v[1]} for m,v in effect.items()}}
                    for (s,b), effect in effects.items()],
        "macros": macros,
        "warnings": ["RR station cap is four; other policies permit nine",
                     "Delay is conditioned on reception time, without censoring correction",
                     "Timing includes warm-up and drain; it is not charged to simulated time",
                     "A mean of run p99s is not a pooled p99"],
    }
    (output / "claim_audit.json").write_text(json.dumps(audit, indent=2) + "\n")
    if not plots:
        return audit
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np
    plt.rcParams.update({"font.family": "serif", "font.size": 8, "axes.labelsize": 8,
                         "legend.fontsize": 7, "pdf.fonttype": 42, "ps.fonttype": 42})
    fig, ax = plt.subplots(figsize=(3.45, 1.95), layout="constrained")
    y = np.arange(4)
    for offset, baseline, color, label in [(-.13, "rr_default", "#24658a", "versus RR4"),
                                          (.13, "max_backlog", "#b15d25", "versus Max-Q")]:
        vals = [effects[s,baseline]["throughput_mbps"] for s in SCENARIOS[2:]]
        ax.errorbar([v[0] for v in vals], y + offset, xerr=[v[1] for v in vals],
                    fmt="o", markersize=3.5, capsize=2, color=color, label=label)
    ax.set_yticks(y, NAMES[2:])
    ax.invert_yaxis()
    ax.set_xlim(0, 33)
    ax.set_xlabel("Paired L-T throughput gain (Mbps)")
    ax.grid(axis="x", color="0.9")
    ax.set_axisbelow(True)
    ax.legend(loc="lower right", frameon=False)
    for ext in ["pdf", "eps"]:
        fig.savefig(output / ("gains." + ext), metadata={"CreationDate": None} if ext == "pdf" else None)
    plt.close(fig)
    fig, ax = plt.subplots(figsize=(3.45, 2.05), layout="constrained")
    x = np.arange(6)
    bottom = np.zeros(6)
    for name, key, color in [("State", "state", "#b6cbd7"), ("Inference", "inference", "#24658a"),
                              ("Projection", "projection", "#b15d25")]:
        vals = [statistics.fmean(r[key + "_mean_us"] for r in latency["rows"] if r["scenario"] == s) / 1000
                for s in SCENARIOS]
        ax.bar(x, vals, bottom=bottom, width=.6, label=name, color=color)
        bottom += vals
    p99 = [statistics.fmean(r["decision_p99_us"] for r in latency["rows"] if r["scenario"] == s)/1000
           for s in SCENARIOS]
    ax.plot(x, p99, "k_", markersize=9, label="Mean run p99")
    ax.axhline(1.5, linestyle="--", color="0.5", linewidth=.8)
    ax.set_ylim(0, 1.8)
    ax.set_xticks(x, ["Sparse", "Normal", "Sat.", "Low\nMCS", "4 STA", "7 STA"])
    ax.set_ylabel("Host computation time (ms)")
    ax.legend(ncol=2, loc="upper left", frameon=False, fontsize=6.5)
    for ext in ["pdf", "eps"]:
        fig.savefig(output / ("latency." + ext), metadata={"CreationDate": None} if ext == "pdf" else None)
    plt.close(fig)
    return audit


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", type=Path, default=ROOT / "results/native_10seed")
    parser.add_argument("--output", type=Path, default=ROOT.parent / "tex")
    parser.add_argument("--no-plots", action="store_true")
    args = parser.parse_args()
    audit = generate(args.results, args.output, not args.no_plots)
    print(f"Validated {audit['network_runs']} network runs and {audit['serial_runs']} timing runs; generated {args.output}")
